fixed tests

diff --git a/startup b/startup
--- a/startup
+++ b/startup
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# functions
+containsElement () {
+  local e
+  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
+  return 1
+}
+
 # locate non-relative script dir
 MAIN_SCRIPT_BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
@@ -18,7 +25,6 @@ then export COMPONENTS_DIRNAME="${MAIN_SCRIPT_DIRNAME}"
 else export COMPONENTS_DIRNAME="${MAIN_SCRIPT_DIRNAME}/.startup"
 fi
 
-
 if [ ! -d "${COMPONENTS_DIRNAME}" ]
 then
  printf "component scripts directory '${COMPONENTS_DIRNAME}' does not exist.\n"
@@ -27,38 +33,64 @@ fi
 
 # get list of components
 
-COMPONENT_SCRIPTS=$(cd $COMPONENTS_DIRNAME; ls)
+COMPONENT_NAMES=$(cd $COMPONENTS_DIRNAME; /usr/bin/ls)
+component_scriptnames_ary=()
+while read -r line; do component_scriptnames_ary+=("$line"); done <<< "${COMPONENT_NAMES}"
+
+# if startup.order is used, cross-check contents
+# not including 'startup' and 'startup.order' files
 
 ORDER_FILE="${COMPONENTS_DIRNAME}/startup.order"
-# check for order file
 if [ -f "${ORDER_FILE}" ]
 then
  export COMPONENT_ORDER=$(cat ${ORDER_FILE})
- # verify every file listed in components exists in executable script form in the .startup directory
+
+ # verify every file listed in components exists in
+ # executable script form in the .startup directory
+
  for component_name in $COMPONENT_ORDER
  do
-  if [ ! -f "${component_name}" ]
+  COMPONENT_SCRIPT="${COMPONENTS_DIRNAME}/${component_name}"
+  if [ ! -f "${COMPONENT_SCRIPT}" ]
   then
-   printf "component startup script '${component_name}' is missing.\n";
+   printf "component startup script '${COMPONENT_SCRIPT}' is missing, but it was listed in startup.order.\n";
+   exit 2
   fi
-  if [ ! -x "${component_name}" ]
+  if [ ! -x "${COMPONENT_SCRIPT}" ]
   then
-   printf "component startup script '${component_name}' is not executable.\n";
+   printf "component startup script '${COMPONENT_SCRIPT}' is not executable.\n";
+   exit 2
   fi
  done
 
- # verify no additional files unlisted in startup.order
- difference=$(comm <(echo "${COMPONENT_ORDER}" | sort) <(echo "${COMPONENT_SCRIPTS}"))
- printf "Difference: $difference\n"
+ # verify that all named components found in script form
+ # exist in the startup.order file
+
+ component_order_ary=()
+ while read -r line; do component_order_ary+=("$line"); done <<< "${COMPONENT_ORDER}"
+
+ for component_scriptname in "${component_scriptnames_ary[@]}"
+ do
+#  printf "checking %s for ordering membership.\n" "$component_scriptname" 1>&2
+  if ! containsElement "${component_scriptname}" "${component_order_ary[@]}"
+  then
+   printf "There is a startup.order file, but script '${component_scriptname}' is not listed in it.\n"
+   exit 2
+  fi
+ done
 else
- printf "# component order is based on filenames. Consider adding a startup.order file to control order of startup.\n"
- export COMPONENT_ORDER="$COMPONENT_SCRIPTS"
+ export COMPONENT_ORDER="$COMPONENT_NAMES"
 fi
 
 if [ -z "${COMPONENT_ORDER}" ]
 then
  printf "There are no component scripts in ${COMPONENTS_DIRNAME}\n";
  exit 2
+fi
+
+if [ ! -f "${ORDER_FILE}" ]
+then
+ printf "# Component order is based on filenames.\n# Consider adding a startup.order file to control order of startup.\n" 1>&2
 fi
 
 # if no components selected, show options and help
@@ -79,21 +111,14 @@ while read -r line; do to_run_ary+=("$line"); done <<< "${TO_RUN}"
 order_ary=()
 while read -r line; do order_ary+=("$line"); done <<< "${COMPONENT_ORDER}"
 
-printf "to_run: %s\n" "${to_run_ary[@]}"
 
 # execute components in order
-containsElement () {
-  local e
-  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
-  return 1
-}
-
 for selected in "${to_run_ary[@]}"
 do
  if containsElement "${selected}" "${order_ary[@]}"
  then
   FULL_SCRIPT_PATH="${COMPONENTS_DIRNAME}/${selected}"
-  printf "executing: %s\n" "${FULL_SCRIPT_PATH}"
+  printf "executing: %s\n" "${FULL_SCRIPT_PATH}" 1>&2
   ( cd ${EXECUTIOND_DIR} && bash ${FULL_SCRIPT_PATH})
   last_status=$?
   if [[ last_status -ne 0 ]]
